### ISSUE TITLE
BG1 Socket Dosn't respond to commands

### ISSUE THREAD

**Issue by matt01** [eschava/broadlink-mqtt#79]
Hi, 

I have recently purchased two of the double gang wall mounted BG1 sockets and have attempted to get them to work with this code.

When I run the mqtt.py script and send it some messages I get the following output, 
```
(testenv1) iot1 ~/broadlink-mqtt # ./mqtt.py 
[2020-07-27 01:10:39,696] DEBUG Connected to 'BG1' Broadlink device at '192.168.51.104' (MAC 24:df:a7:a4:d7:21) and started listening for commands at MQTT topic having prefix 'broadlink/a4_d7_21/' 
[2020-07-27 01:10:39,700] DEBUG Connected to MQTT broker, subscribing to topic broadlink/#
[2020-07-27 01:10:44,747] DEBUG Received MQTT message broadlink/a4_d7_21/power/1 on
[2020-07-27 01:10:44,747] DEBUG Setting power state of socket 1 to True
[2020-07-27 01:10:44,752] DEBUG Received MQTT message broadlink/a4_d7_21/power/2 on
[2020-07-27 01:10:44,753] DEBUG Setting power state of socket 2 to True
```
However, the socket never switches on. This is the same for both of them.
The android app works without any issues and I have updated the firmware on one of the socket.
I am also using the barnybug/python-broadlink@add_bgelectrical_sockets version of the python-broadlink library.

Does anybody know why this might not be working? 

[Here](https://people.bath.ac.uk/mr245/bg1_socket1.txt) is a dump of the network traffic on port UDP/80.

Thanks, 

Matt.

**Comment by ElectricImpossible** [comment]
I had slight issues getting a single BG1 working initially but worked well until I added a second device!

Have you managed to get a single socket working yet? If not then I would recommend focusing on that first.

Im using firmware 57053 (hopefully this shows that recent firmware still works) and was able to see similar debug output when using the Android app or MQTT topic to toggle the sockets. When adding the second socket it seemed to add it to the original socket as a slave and this broke my setup.

I used @cgorms's advice here to break them up.

https://www.reddit.com/r/HOOBS/comments/g8fhvn/no_json_response/fowb02u?utm_source=share&utm_medium=web2x

**Comment by matt01** [comment]
Setting up the sockets using the broadlink-cli makes them work for me, it also makes them all work, at the same time :+1: 

I do have another socket, which is one of these: https://www.bgelectrical.uk/wiring-devices/moulded/smart-sockets#AHC/U-01 , which doesn't work but I think this is a different issue as the product id its returning is different to the other sockets.

Thanks @ElectricImpossible

**Comment by Sinbad95** [comment]
I appreciate that this issue is closed but I have had the same issue and found that the solution that worked for ElectricImpossible & matt01 didn't work for me. I did find another solution though which may help people who have the same experience.

The socket had firmware version 46042.

When I tried this I had MQTT Explorer running and the command line on the Home Assistance machine set ready to run mqtt.py (with the configuration of my socket already entered).

-  Using the BG Home app, follow the instructions to connect using the AP method. 
            --There seems to be a limitation with Android 9, which I encountered. It will fail to find the socket, keep retrying until it 
                gives you the option to go to your WiFi settings. 
            -- Select the WiFi connection offered by the socket (has the last 6 characters of the MAC of the socket in the name)
- Select the SSID you want it to connect to and provide the credentials
- While it is saying connecting to your WiFi, start the mqtt.py
- Now when it says your device is connected to your WiFi you should see traffic. Wait until you see this traffic before you proceed, it should take less that 30 seconds 
- You can now add the socket to a room and give it a name in the BG Home app.

I could then see the MQTT traffic and read & set it via Home Assistant via Node Red.
